course/urls.py
from django.urls import path

from . import views

app_name = 'course'
urlpatterns = [path("", views.index, name="index"),
               path("<int:course_id>", views.course, name="course"),
               path("register", views.register, name="register"),
               path("register/<int:course_id>",
                    views.temp_register, name="temp_register"),
               path("deregister/<int:course_id>",
                    views.temp_deregister, name="deregister"),
               path("confirm_register", views.confirm_register,
                    name="confirm_register"),
               path("mycourse", views.mycourse, name="mycourse"),
               path("status/<int:course_id>", views.status, name="status"),
               ]

course_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('course/',include("course.urls")),
    path('users/',include("users.urls")),
    path('',include("users.urls")),
]

users/urls.py
from django.urls import path

from . import views

app_name="users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
]

course/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Student(models.Model) :
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    std_id = models.CharField(max_length=10)

    def __str__(self):
        return f"user : {self.user.username} ID : {self.std_id} Name : {self.user.first_name} {self.user.last_name}"


class Course(models.Model):
    code = models.CharField(max_length=5)
    name = models.CharField(max_length = 64)
    semester = models.IntegerField()
    year = models.IntegerField()
    amount = models.IntegerField()
    status = models.BooleanField()
    registered = models.ManyToManyField(Student,blank = True)

    def isfull(self) :
        if self.registered.count() == self.amount :
            return True
        return False
        
    def __str__(self):
        return f"{self.name} ( {self.code} )"


class Temp_register(models.Model) :
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    register = models.ManyToManyField(Course,blank = True)
    def __str__(self) :
        return f"{self.user.username} registering {self.register.count()} courses"

course/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages


# Create your views here.

from .models import *


def index(request):
    if request.user.is_authenticated:
        return render(request, "course/index.html", {
            "courses": Course.objects.all()
        })

    else:
        return HttpResponseRedirect(reverse("users:login"))


def course(request, course_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    this_course = Course.objects.get(id=course_id)

    return render(request, "course/course.html", {
        "course": this_course,
    })


def register(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    username = request.user.username
    open_course = []
    user_temp = Temp_register.objects.get_or_create(user=request.user)[0]
    temp_registered = user_temp.register.all()
    registered_course = []
    for course in Course.objects.all():
        for student in course.registered.all():
            if request.user == student.user:
                registered_course.append(course)

    for course in Course.objects.all():

        if (course not in user_temp.register.all()):
            open_course.append(
                (course, course.registered.count(), course.isfull()))

        if course.isfull():
            course.status = False
        elif (not course.isfull()) & (course.status == False):
            course.status = False
        else:
            course.status = True
        course.save()

    return render(request, "course/register.html", {
        "username": username,
        "open_courses": open_course,
        "temp_registered": temp_registered,
        "registered_course": registered_course,
    })


def temp_register(request, course_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))

    user_temp = Temp_register.objects.get_or_create(user=request.user)[0]
    this_course = Course.objects.get(id=course_id)

    user_temp.register.add(this_course)
    user_temp.save()
    return HttpResponseRedirect(reverse("course:register"))


def temp_deregister(request, course_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))

    user_temp = Temp_register.objects.get_or_create(user=request.user)[0]
    this_course = Course.objects.get(id=course_id)

    user_temp.register.remove(this_course)
    user_temp.save()
    return HttpResponseRedirect(reverse("course:register"))


def confirm_register(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))

    user_student = Student.objects.get(user=request.user)
    user_temp = Temp_register.objects.get_or_create(user=request.user)[0]

    registered_course = []
    for course in Course.objects.all():
        for student in course.registered.all():
            if request.user == student.user:
                registered_course.append(course)
    for course in registered_course:
        course.registered.remove(user_student)
        course.save()
    for course in user_temp.register.all():
        if user_student not in course.registered.all():
            course.registered.add(user_student)
        if course.isfull():
            course.status = False
        else:
            course.status = True
        course.save()
    return HttpResponseRedirect(reverse("course:mycourse"))


def mycourse(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))

    username = request.user.username
    registered_courses = []
    for course in Course.objects.all():
        if course.isfull():
            course.status = False
        else:
            course.status = True
        course.save()
        for student in course.registered.all():
            if username == student.user.username:
                registered_courses.append(course)

    return render(request, "course/mycourse.html", {
        "registered_courses": registered_courses,
    })


def status(request, course_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    course = Course.objects.get(id=course_id)
    course.status = not course.status
    course.save()
    return HttpResponseRedirect(reverse("course:course", args=(course.id, )))

course/templates/course/course.html
{% extends "course/layout.html" %} 
{% block body %}

<h1>Course {{course.id}}</h1>
<ul>
    <li><b>Course name :</b> {{ course.name }}</li>
    <li><b>Course code :</b> {{ course.code }}</li>
    <li><b>Semester :</b> {{ course.semester }}</li>
    <li><b>Year :</b> {{course.year}}</li>
    <li><b>Quota amount :</b> {{course.amount}}</li>
    <li><b>Status :</b> 
        {% if course.status %}
        <b style = "color: rgb(0, 255, 21);">
        Open
        </b>
        {% else %}
        <b style = "color: rgb(201, 29, 29);">
        Close
        </b>
        {% endif %}
    </b></li>
    
    {% if request.user.is_superuser %}
        {% if course.status %}
        <a href='{%url "course:status" course.id %}' class="button">Close</a>
        {% else %}
        <a href='{%url "course:status" course.id %}' class="button">Open</a>
        {% endif %}
    {% endif %}


</ul>
    
    <ol>
    {% if request.user.is_superuser %}
    <b>Students :</b>
    <br>
    {% if course.registered.all|length <= 0 %}
    <br>
    No student registered
    {% endif %}
    
    <br>
    {% for student in course.registered.all %}
    <li>{{student}}</li>
    {% endfor %}
    {% endif %}
</ol>
<br>
<a href='{%url "course:index" %}' class="button">Back</a>

{% endblock %}

course/templates/course/index.html
{% extends "course/layout.html" %}

{% block body %}
    
    <h1>Courses</h1>
    <ul>
        {% for course in courses %}
            <li><b><a href='{%url "course:course" course.id %}' class = 'button1'><span>{{course}}</span></a></b></li>
        {% endfor %}
    </ul>
    <a href='{%url "users:index" %}' class="button">Back</a>
{% endblock %}

course/templates/course/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <link href = "{% static 'course/css/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <style>
    body {
  background-image: url("{% static 'course/img/wallpaper.jpg' %}");
  background-size: cover;
    }
    body {
    padding-top: 3%;
    padding-left: 5%;
    padding-right: 5%;
    padding-bottom: 3%;
    }
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
    .button {
                background-color: #000000;
                border: none;
                color: white;
                padding: 6px 32px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                border-radius: 12px;
                transition-duration: 0.4s;
                }
    .button:hover {
                background-color: #444444;
                color: white;
                }
    ul {
            list-style-type: square;
            margin: 50px;
            padding: 20px;
            }
    li {
        margin-bottom: 20px;
        }
    .wrapper {
        text-align: right;
        margin-right: 40%;
    }
    table{
        width: 75%;
        table-layout: fixed;
    }
        .button1 {
            background-color:black;
            border: none;
            color: whitesmoke;
            padding: 15px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 12px;
            }
        .button1 span {
            cursor: pointer;
            display: inline-block;
            position: relative;
            transition: 0.5s;
            }

        .button1 span:after {
            content: '\00bb';
            position: absolute;
            opacity: 0;
            top: 0;
            right: -20px;
            transition: 0.5s;
            }

        .button1:hover span {
            padding-right: 25px;
            }

        .button1:hover span:after {
            opacity: 1;
            right: 0;
            }
        .button2 {
            background-color:rgb(0, 0, 0);
            border: 20px ;
            color: whitesmoke;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
            transition-duration: 0.4s;
            border-radius: 12px;
            }
        .button2:hover {
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
            background-color: #e24040;
            color: white;
            }
        .fakebutton {
                background-color: #ff0000;
                border: none;
                color: white;
                padding: 6px 42px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                border-radius: 12px;
                cursor: pointer;
        }
    </style>
    <head>
        <title>Courses</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

course/templates/course/mycourse.html
{% extends "course/layout.html" %}
{% block body %}

    <h1>My Courses</h1>
    <ul>{% if registered_courses|length <= 0 %}
            <b style = "color: red;">Not registered in any course</b>
        {% endif %}
        {% for course in registered_courses %}
            <li><b>{{course}}</li></b>
        {% endfor %}
    </ul>
    <a href='{%url "users:index" %}' class = "button">Back</a>
{% endblock %}

course/templates/course/register.html
{% extends "course/layout.html" %}
{% block body %}
    <h1>Availiable Courses for {{username}}</h1>
    <br>
    {% if request.user.is_superuser %}
    <table>
    
        {% for course,num,full in open_courses %}
            <tr><th><b><a href='{%url "course:course" course.id %}'>{{course}}</a></b></th>
                <th><b>{{num}} / {{course.amount}}</b></th>
                {% if full %} 
                    {% if course in registered_course and course not in temp_registered%}
                <th><div class="wrapper"><a href='{%url "course:temp_register" course.id %}' class = "button">Register</a></div></th>
                    {% else %}
                <th><div class="wrapper"><button class="fakebutton"><b>FULL</b></button></div></th>
                    {% endif %}
                {% elif not course.status %}
                <th><div class="wrapper"><button class="fakebutton" style="padding: 6px 30px;"><b>CLOSED</b></button></div></th>
                {% else%}
                <th><div class="wrapper"><a href='{%url "course:temp_register" course.id %}' class = "button" >Register</a></div></th>
                {% endif %}
            </tr>
        {% endfor %}
    
    </table>
    <br>
    <hr style="height:3px;border-width:0;color:black;background-color:black">
    <br>
    <h1>Willing to register</h1>
    <br>
    <table>
        {% for course in temp_registered %}
            <tr><th><b><a href='{%url "course:course" course.id %}'>{{course}}</a></b></th>
                <th><div class="wrapper"><a href='{%url "course:deregister" course.id %}' class = "button" >Remove</a></div></th>
            </tr>
        {% empty %}
            <div style="color:red; text-indent: 17%; font-size: 21px;"><b>Not registered in any course. ( Confirm to cancel all courses. )</b></div>
        
        {% endfor %}
    </table>
    {% else %}
    <table>
        {% for course,num,full in open_courses %}
        <tr><th><b>{{course}}</b></th>
            <th><b>{{num}} / {{course.amount}}</b></th>
                {% if full %} 
                    {% if course in registered_course and course not in temp_registered%}
                    <th><div class="wrapper"><a href='{%url "course:temp_register" course.id %}' class = "button">Register</a></div></th>
                    {% else %}
                    <th><div class="wrapper"><button class="fakebutton"><b>FULL</b></button></div></th>
                    {% endif %}
                {% elif not course.status %}
                    <th><div class="wrapper"><button class="fakebutton" style="padding: 6px 30px;;"><b>CLOSED</b></button></div></th>
                {% else %}
            <th><div class="wrapper"><a href='{%url "course:temp_register" course.id %}' class = "button">Register</a></div></th>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    <br>
    <hr style="height:3px;border-width:0;color:black;background-color:black">
    <br>
    <h1>Willing to register</h1>
    <br>
    <table>
        {% for course in temp_registered %}
            <tr><th><b>{{course}}</b></th>
                <th><div class="wrapper"><a href='{%url "course:deregister" course.id %}' class = "button">Remove</a></div></th>
            </tr>
        {% empty %}
            <div style="color:red; text-indent: 17%; font-size: 21px;"><b>Not registered in any course. ( Confirm to cancel all courses. )</b></div>
        
        {% endfor %}
    </table>
    {% endif %}
    <br>
    <br>
    <br>
    <div class="wrapper"><b><a href='{%url "course:confirm_register" %}' class = "button2">Confirm Registration</a></b></div>
    <a href='{%url "users:index" %}' class = "button">Back</a>
{% endblock %}