course/urls.py
from django.urls import path

from . import views

app_name = 'course'
urlpatterns = [path("", views.index, name="index"),
               path("<int:course_id>", views.course, name="course"),
               path("register", views.register, name="register"),
               path("register/<int:course_id>",
                    views.temp_register, name="temp_register"),
               path("deregister/<int:course_id>",
                    views.temp_deregister, name="deregister"),
               path("confirm_register", views.confirm_register,
                    name="confirm_register"),
               path("mycourse", views.mycourse, name="mycourse"),
               path("status/<int:course_id>", views.status, name="status"),
               ]

course_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('course/',include("course.urls")),
    path('users/',include("users.urls")),
    path('',include("users.urls")),
]

users/urls.py
from django.urls import path

from . import views

app_name="users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
# Create your views here.
import sys
sys.path.append('../')
from course.models import *

def index(request):
    if request.user.is_authenticated:
        return render(request, "users/index.html")
    else:
        return HttpResponseRedirect(reverse("users:login"))

def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:index"))

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("users:index"))
        else:
            return render(request, "users/login.html", {"fail": "Invalid credential"})
    return render(request, "users/login.html")
    
    

def logout_view(request):
    logout(request)
    messages.success(request, "Logged out.")
    return render(request, "users/login.html", {
        "messages": messages.get_messages(request)
    })


def register_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        re_password = request.POST["re_password"]
        email = request.POST["email"]
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        std_id = request.POST["std_id"]
        if User.objects.filter(username = username).first():
            return render(request, "users/register.html", {"fail": "This username is already taken"})
        if Student.objects.filter(std_id = std_id).first():
            return render(request, "users/register.html", {"fail": "Student ID already taken"})
        if (not std_id.isnumeric()) or (len(std_id) > 10 or len(std_id) < 10):
            return render(request, "users/register.html", {"fail": "Student ID must be an integer with length of 10"})
        if password != re_password:
            return render(request, "users/register.html", {"fail": "Invalid password confirm"})
        add_user = User(username=username, email=email,
                        first_name=first_name, last_name=last_name)
        bond_id = Student(user = add_user,std_id = std_id)
        add_user.set_password(password)
        
        add_user.save()
        bond_id.save()
        return render(request, "users/login.html")
    return render(request, "users/register.html")

users/templates/users/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <link href = "{% static 'users/css/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <style>body {
        background-image: url("{% static 'users/img/index.jpg' %}");
        background-size: cover;
    }
        body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
        .button1 {
            background-color:black;
            border: none;
            color: whitesmoke;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 12px;
            }
            .button1 span {
            cursor: pointer;
            display: inline-block;
            position: relative;
            transition: 0.5s;
            }

            .button1 span:after {
            content: '\00bb';
            position: absolute;
            opacity: 0;
            top: 0;
            right: -20px;
            transition: 0.5s;
            }

            .button1:hover span {
            padding-right: 25px;
            }

            .button1:hover span:after {
            opacity: 1;
            right: 0;
            }
            .button2 {
            background-color:rgb(233, 125, 215);
            border: 1px solid #000000;
            color: whitesmoke;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
            transition-duration: 0.4s;
            border-radius: 12px;
            }
            .button2:hover {
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
            background-color: #e24040;
            color: white;
            }
            ul {
            list-style-type: square;
            margin: 0;
            padding: 20px;
            }
            
    </style>
    <head>
        <title>Course Registration</title>
    </head>
    <body>
        
        <h1>Welcome, {{ request.user.first_name }}</h1>

    <ul>
    <li>Username: {{ request.user.username }}</li>
    </ul>

    <a href="{% url 'course:mycourse' %}" class="button1"><span>My Courses</span></a>
    <br>
    <a href="{% url 'course:register' %}" class="button1"><span>Register Courses</span></a>
    <br>
    {% if request.user.is_superuser %}
    <a href="{% url 'course:index' %}" class="button1"><span>Course Lists</span></a>
    {% else %}
    <a href="{% url 'course:index' %}" class="button1"><span>Courses Info</span></a>
    {% endif %}

    <br>
    <br>
    <a href="{% url 'users:logout' %}" class="button2">Log out</a>

    </body>
</html>

users/templates/users/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <link href = "{% static 'users/css/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <style>body {
        background-image: url("{% static 'users/img/log_reg.jpg' %}");
        background-size: cover;
    }
        body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
        input[type=text], input[type=password] ,input[type=int]{
        width: 300px;
        padding: 12px 20px;
        margin: 8px 8px;
        display: inline-block;
        border: 1px solid #ccc;
        box-sizing: border-box;
        }
        .container {
            
        margin: auto;
        width: 50%;
        padding: 32px;
        text-align: center;
        border: 10px solid #000000;
        }
    </style>
    <head>
        <title>Course Registration</title>
    </head>
    <body>
        
        {% block body %}
        {% endblock %}
        
    </body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}


{% block body %}

    <style>
    .button {
    background-color: #000000;
    border: none;
    color: white;
    padding: 12px 64px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    border-radius: 12px;
    transition-duration: 0.4s;
    }
    .button:hover {
    background-color: #414141;
    color: white;
    }
    
    </style>
    
    <div class="container">
    
        <h1>Course Registration</h1>    
    
    <br>   
    <br>
    <br>
    {% if messages %}
        {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} style="color: red;"><b>{{ message }}</b></div>
        {% endfor %}
        <br>
    {% endif %}
    {%if fail%} <div style="color: red;"><b>{{fail}}</b></div><br> {%endif%}

    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username" required>
        <br>
        <input type="password" name="password" placeholder="Password" required>
        <br>
        <input type="submit" value="Login" class = "button">
    </form>
    <br>
    <p>Doesn't have an account?</p>
    <a href="{% url 'users:register' %}" class = "button">Register</a>
</div>

{% endblock %}

users/templates/users/register.html
{% extends "users/layout.html" %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Register</title>

        <!-- load stylesheets -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400">  
                                                  
    </head>
    

{% block body %}
        <style>
            .button {
                background-color: #000000;
                border: none;
                color: white;
                padding: 12px 64px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                border-radius: 12px;
                transition-duration: 0.4s;
                }
                .button:hover {
                background-color: #444444;
                color: white;
                }
        </style>
        

        <!-- Header -->
        <div class="container">
        <header>
            <a href="{% url 'course:index' %}" class = "button">
                <h1>Course Registration</h1>    
            </a>            
        </header>
        
        <!-- Login Form -->
        
        <section>
                                
            <header>
                <h2>Register Form</h2>
            </header>
                                
            <div>
                <p>Please enter your infromation
                </p>
                {%if fail%} <div style="color: red;"><b>{{fail}}</b></div><br> {%endif%}

                <form action="{% url 'users:register' %}" method="post" class="contact-form">
                    {% csrf_token %}
                    <div>
                        <input type="text"  name="username" placeholder="Username" required/>
                    </div>
                    <br>
                    <div>
                        <input type="password"  name="password" placeholder="Password" required/>
                    </div>
                    <br>
                    <div>
                        <input type="password"  name="re_password" placeholder="Confirm Password" required/>
                    </div>
                    <br>
                    <div>
                        <input type="text"  name="first_name" placeholder="First Name" required/>
                    </div>
                    <br>
                    <div>
                        <input type="text"  name="last_name" placeholder="Last Name" required/>
                    </div>
                    <br>
                    <div>
                        <input type="int"  name="std_id" placeholder="Student ID" required/>
                    </div>
                    <br>
                    <div class="form-group">
                        <input type="text"  name="email" placeholder="Email" required/>
                    </div>
                    <br>
                    <br>
                    <input type="submit" value ="Confirm" class="button"></input>

                </form>                           
            </div>            

        </section> 
        <br>
        <a href="{% url 'users:index' %}" class = "button">Back</a>
    </div>
       

</html>
{% endblock %}